/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookRouteImport } from './routes/cook'
import { Route as EatRouteImport } from './routes/eat'
import { Route as OutRouteImport } from './routes/out'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RecipeIdRouteImport } from './routes/recipe.$id'
import { Route as VenueIdRouteImport } from './routes/venue.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookRoute = CookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const EatRoute = EatRouteImport.update({
  id: '/eat',
  path: '/eat',
  getParentRoute: () => rootRouteImport,
} as any)
const OutRoute = OutRouteImport.update({
  id: '/out',
  path: '/out',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueIdRoute = VenueIdRouteImport.update({
  id: '/venue/$id',
  path: '/venue/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cook': typeof CookRoute
  '/eat': typeof EatRoute
  '/out': typeof OutRoute
  '/saved': typeof SavedRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/venue/$id': typeof VenueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cook': typeof CookRoute
  '/eat': typeof EatRoute
  '/out': typeof OutRoute
  '/saved': typeof SavedRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/venue/$id': typeof VenueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cook': typeof CookRoute
  '/eat': typeof EatRoute
  '/out': typeof OutRoute
  '/saved': typeof SavedRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/venue/$id': typeof VenueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cook'
    | '/eat'
    | '/out'
    | '/saved'
    | '/recipe/$id'
    | '/venue/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cook'
    | '/eat'
    | '/out'
    | '/saved'
    | '/recipe/$id'
    | '/venue/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cook'
    | '/eat'
    | '/out'
    | '/saved'
    | '/recipe/$id'
    | '/venue/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CookRoute: typeof CookRoute
  EatRoute: typeof EatRoute
  OutRoute: typeof OutRoute
  SavedRoute: typeof SavedRoute
  RecipeIdRoute: typeof RecipeIdRoute
  VenueIdRoute: typeof VenueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook': {
      id: '/cook'
      path: '/cook'
      fullPath: '/cook'
      preLoaderRoute: typeof CookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eat': {
      id: '/eat'
      path: '/eat'
      fullPath: '/eat'
      preLoaderRoute: typeof EatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/out': {
      id: '/out'
      path: '/out'
      fullPath: '/out'
      preLoaderRoute: typeof OutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$id': {
      id: '/venue/$id'
      path: '/venue/$id'
      fullPath: '/venue/$id'
      preLoaderRoute: typeof VenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CookRoute: CookRoute,
  EatRoute: EatRoute,
  OutRoute: OutRoute,
  SavedRoute: SavedRoute,
  RecipeIdRoute: RecipeIdRoute,
  VenueIdRoute: VenueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
