import type { Venue } from "./food";

/**
 * Shown when no venue provider key is configured, when the daily budget is
 * spent, or when the provider errors. Clearly labelled as samples in the UI.
 */
export const SAMPLE_VENUES: Venue[] = [
  {
    id: "sample-lumen",
    name: "Lumen Dining Room",
    address: "12 Ashgrove Lane",
    cuisine: "Modern European",
    rating: 4.6,
    ratingCount: 812,
    price: "PRICE_LEVEL_EXPENSIVE",
    openNow: true,
    hours: ["Monday: 6:00 – 11:00 PM", "Tuesday: 6:00 – 11:00 PM"],
    phone: null,
    website: null,
    photoUrl: null,
    lat: null,
    lng: null,
  },
  {
    id: "sample-moto",
    name: "Moto Noodle Bar",
    address: "3 Canal Street",
    cuisine: "Ramen",
    rating: 4.4,
    ratingCount: 1943,
    price: "PRICE_LEVEL_INEXPENSIVE",
    openNow: true,
    hours: [],
    phone: null,
    website: null,
    photoUrl: null,
    lat: null,
    lng: null,
  },
  {
    id: "sample-copper",
    name: "Copper & Cardamom",
    address: "88 Fairview Road",
    cuisine: "South Indian",
    rating: 4.7,
    ratingCount: 604,
    price: "PRICE_LEVEL_MODERATE",
    openNow: false,
    hours: [],
    phone: null,
    website: null,
    photoUrl: null,
    lat: null,
    lng: null,
  },
  {
    id: "sample-perch",
    name: "The Perch",
    address: "5 Market Square",
    cuisine: "Wine bar",
    rating: 4.3,
    ratingCount: 388,
    price: "PRICE_LEVEL_MODERATE",
    openNow: true,
    hours: [],
    phone: null,
    website: null,
    photoUrl: null,
    lat: null,
    lng: null,
  },
  {
    id: "sample-saltbox",
    name: "Saltbox Bakery",
    address: "41 Rowan Street",
    cuisine: "Bakery",
    rating: 4.8,
    ratingCount: 1220,
    price: "PRICE_LEVEL_INEXPENSIVE",
    openNow: true,
    hours: [],
    phone: null,
    website: null,
    photoUrl: null,
    lat: null,
    lng: null,
  },
  {
    id: "sample-ember",
    name: "Ember Yard Grill",
    address: "17 Kiln Walk",
    cuisine: "Barbecue",
    rating: 4.5,
    ratingCount: 976,
    price: "PRICE_LEVEL_MODERATE",
    openNow: false,
    hours: [],
    phone: null,
    website: null,
    photoUrl: null,
    lat: null,
    lng: null,
  },
];

export function sampleVenue(id: string): Venue | null {
  return SAMPLE_VENUES.find((v) => v.id === id) ?? null;
}
