/**
 * High-End Premium South African Restaurant database for What's Good
 * Focused on the Cape Town culinary ecosystem with true geographic coordinates.
 */

export interface SouthAfricanEatery {
  id: string;
  name: string;
  address: string;
  cuisine: string;
  vibeMatch: string;
  fallbackDistance: string; // fallback if geolocation is denied
  rating: number;
  priceSymbol: 'R' | 'RR' | 'RRR' | 'RRRR'; // South African Rand pricing Tier
  voucherOffer: string;
  signatureOrder: string;
  signatureDescription: string;
  signatureIngredients: string[];
  digestiveNote: string;
  externalLink: string;
  latitude: number; // For real distance sorting
  longitude: number;
  phone: string;
  estimatedWait: string;
  photoUrl?: string; // Optional override for dynamic sources (e.g. Google Places)
}

export const SOUTH_AFRICAN_EATERIES: SouthAfricanEatery[] = [
  {
    id: 'eat-kloof-house',
    name: 'Kloof Street House',
    address: '30 Kloof St, Gardens, Cape Town',
    cuisine: 'Mediterranean-inspired Brasserie',
    vibeMatch: 'feeling fancy',
    fallbackDistance: '1.4 km from City Bowl',
    rating: 4.8,
    priceSymbol: 'RRR',
    voucherOffer: 'Complimentary glass of local MCC Sparkling Wine on arrival',
    signatureOrder: 'Char-grilled Fillet with Truffle Butter',
    signatureDescription: 'Perfectly aged free-range South African beef fillet, flame-licked and crowned with rich, whipped black truffle butter and charred asparagus.',
    signatureIngredients: ['Aged Free-range Beef Fillet', 'Black Truffle Butter', 'Maldon Smoked Salt', 'Grilled Asparagus'],
    digestiveNote: 'Beef provides protein and iron; grilled asparagus adds folate and fibre. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.kloofstreethouse.co.za/',
    latitude: -33.9295,
    longitude: 18.4098,
    phone: '+27214220266',
    estimatedWait: 'Reservation Advised'
  },
  {
    id: 'eat-nandos-rondebosch',
    name: "Nando's Rondebosch",
    address: '79 Main Rd, Rondebosch, Cape Town',
    cuisine: 'Afro-Portuguese Flame Grill',
    vibeMatch: 'craving something bold & spicy',
    fallbackDistance: '0.2 km from Main Rd',
    rating: 4.6,
    priceSymbol: 'R',
    voucherOffer: 'Completely free Spicy Peri-Chips upgrade with any ¼ Chicken',
    signatureOrder: 'Flame-Grilled ¼ Chicken & Spicy Rice',
    signatureDescription: 'Succulent free-range local chicken marinated for 24 hours in wild herbs and peri-peri, flame-grilled to basting perfection.',
    signatureIngredients: ['Local Quarter Chicken', 'Birds Eye Chili Marinade', 'Lemon Butter Glaze', 'Savory Turmeric Rice'],
    digestiveNote: 'Grilled chicken is a lean protein source. Peri-peri sauces are chili-based; spicy food may cause discomfort for some people. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.nandos.co.za/',
    latitude: -33.9632,
    longitude: 18.4712,
    phone: '+27216854124',
    estimatedWait: '5 - 10 min'
  },
  {
    id: 'eat-chefswarehouse',
    name: "Chiefs Warehouse Beau Constantia",
    address: 'Constantia Main Rd, Constantia, Cape Town',
    cuisine: 'Modern Global Tapas',
    vibeMatch: 'treating myself',
    fallbackDistance: '12.5 km from City Bowl',
    rating: 4.9,
    priceSymbol: 'RRRR',
    voucherOffer: 'Complimentary premium wine pairing with the signature tapas menu',
    signatureOrder: 'Coal-Seared Yellowfin Tuna with Sesame',
    signatureDescription: 'Searing yellowfin tuna over open red-hot coals, combined with sweet ginger amino reduction, radish discs, and fermented wasabi aioli.',
    signatureIngredients: ['Fresh Yellowfin Tuna', 'Fermented Wasabi Seed', 'Pickled Radish', 'Wild Sesame Oil Shavings'],
    digestiveNote: 'Yellowfin tuna is rich in omega-3 fatty acids and protein. Fermented condiments add variety to a meal. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.chefswarehouse.co.za/',
    latitude: -34.0152,
    longitude: 18.4239,
    phone: '+27217948632',
    estimatedWait: 'Pre-booking Required'
  },
  {
    id: 'eat-roxy-latenight',
    name: 'Roxy Late Night',
    address: '14 Chapel Rd, Rosebank, Cape Town',
    cuisine: 'Cozy Comfort Kitchen',
    vibeMatch: 'tired & cosy',
    fallbackDistance: '0.5 km from Rosebank Residence',
    rating: 4.5,
    priceSymbol: 'R',
    voucherOffer: '10% student & young professional discount on all gourmet melts',
    signatureOrder: 'The Midnight Cheese & Bacon Toastie',
    signatureDescription: 'Thick, hand-sliced artisanal farm bread toasted crisp with mature South African cheddar, crispy local bacon, and a sweet red onion marmalade.',
    signatureIngredients: ['Artisanal Farm Bread', 'Mature Cheddar Cheese', 'Crisp Back Bacon', 'Sweet Red Onion Marmalade'],
    digestiveNote: 'A warm, hearty toasted sandwich good for winding down. Rooibos tea alongside is a naturally caffeine-free herbal option. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.roxylatenight.co.za/',
    latitude: -33.9592,
    longitude: 18.4682,
    phone: '+27216891230',
    estimatedWait: '10 - 15 min'
  },
  {
    id: 'eat-oceanbasket-claremont',
    name: 'Ocean Basket Cavendish',
    address: 'Cavendish Square, Claremont, Cape Town',
    cuisine: 'Mediterranean Seafood Grill',
    vibeMatch: 'something fresh & light',
    fallbackDistance: '2.1 km from Southern Suburbs',
    rating: 4.4,
    priceSymbol: 'RR',
    voucherOffer: 'Complimentary side portion of crispy flash-fried calamari heads',
    signatureOrder: 'Prince Prawn & Yellow Rice Platter',
    signatureDescription: 'Plump ocean prawns sizzled in signature garlic lemon-butter sauce, served over a bed of fluffy, hot yellow rice and fresh herbs.',
    signatureIngredients: ['Ocean Prince Prawns', 'Lemon-Garlic Butter', 'Savory Yellow Rice', 'Fresh Garden Herbs'],
    digestiveNote: 'Prawns are a low-fat, high-protein seafood with zinc and iodine. Seafood is generally easy to digest for most people. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.oceanbasket.co.za/',
    latitude: -33.9796,
    longitude: 18.4651,
    phone: '+27216744312',
    estimatedWait: '15 - 20 min'
  },
  {
    id: 'eat-hudsons-claremont',
    name: "Hudson's Burger Joint",
    address: '25 Protea Rd, Claremont, Cape Town',
    cuisine: 'Artisan Burgers & Craft Beer',
    vibeMatch: 'lazy Sunday energy',
    fallbackDistance: '2.3 km from Southern Suburbs',
    rating: 4.7,
    priceSymbol: 'RR',
    voucherOffer: 'Free portion of hand-battered crispy onion rings with any craft burger',
    signatureOrder: 'The Player Beef & Avocado Burger',
    signatureDescription: 'Grass-fed beef patty layered thin with wood-smoked bacon, local feta, freshly smashed avocado, and chili jam on a toasted squarcle bun.',
    signatureIngredients: ['Grass-fed Beef Patty', 'Feta Cheese crumble', 'Fresh Avocado smash', 'Sweet Chili Jam'],
    digestiveNote: 'Avocado contains healthy monounsaturated fats and potassium. Grass-fed beef provides protein, iron, and B vitamins. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://thehudsons.co.za/',
    latitude: -33.9805,
    longitude: 18.4646,
    phone: '+27216745152',
    estimatedWait: '10 - 15 min'
  },
  {
    id: 'eat-bellybeast',
    name: 'Belly of the Beast',
    address: '110 Harrington St, Cape Town Central',
    cuisine: 'Modern South African Bistronomy',
    vibeMatch: 'need comfort food',
    fallbackDistance: '3.6 km from Gardens',
    rating: 4.9,
    priceSymbol: 'RRRR',
    voucherOffer: 'A complimentary artisanal digestif liqueur selection on host table',
    signatureOrder: 'Slow-Braised Karoo Lamb Neck',
    signatureDescription: 'Artfully braised Karoo lamb neck cooked over 12 hours in rich red wine sauce, served with creamed parsnip puree and pickling onions.',
    signatureIngredients: ['Karoo Lamb Neck', 'Parsnip Root', 'Local Shiraz Reduction', 'Pearl Onions'],
    digestiveNote: 'Long, slow braising makes lamb tender and easy to chew. Karoo lamb is free-range and provides protein and iron. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.bellyofthebeast.co.za/',
    latitude: -33.9287,
    longitude: 18.4231,
    phone: '+27762645691',
    estimatedWait: 'Strict Booking Only'
  },
  {
    id: 'eat-cocoawah',
    name: 'Cocoa Wah Wah',
    address: '18 Main Rd, Rondebosch, Cape Town',
    cuisine: 'Warm Local Bistro & Cafe',
    vibeMatch: 'tired & cosy',
    fallbackDistance: '0.4 km from Rondebosch Substation',
    rating: 4.5,
    priceSymbol: 'R',
    voucherOffer: 'A free upgrade to a double espresso shot or marshmallow cocoa melt',
    signatureOrder: 'Toasted Chicken Mayonnaise Flat',
    signatureDescription: 'Poached chicken breast pulled and folded with homemade cream mayo, melted white cheddar, and grilled on flat stone ciabatta.',
    signatureIngredients: ['Pulled Chicken Breast', 'Artisanal Ciabatta', 'Cream Mayonnaise', 'White Cheddar Shavings'],
    digestiveNote: 'A mild, simple dish that suits most tastes. Pulled chicken on ciabatta is easy on the stomach and a solid source of lean protein. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://cocoawahwah.co.za/',
    latitude: -33.9619,
    longitude: 18.4716,
    phone: '+27216863612',
    estimatedWait: '5 - 10 min'
  },
  {
    id: 'eat-codfather-campsbay',
    name: 'The Codfather Seafood & Sushi',
    address: '37 The Camps Bay Dr, Camps Bay, Cape Town',
    cuisine: 'Seafood',
    vibeMatch: 'something fresh & light',
    fallbackDistance: '7.8 km from City Bowl',
    rating: 4.8,
    priceSymbol: 'RRR',
    voucherOffer: 'Complimentary portion of their famous butter-garlic seafood basting sauce with any platter',
    signatureOrder: 'Butter-Basted Prince Prawns & Kingklip',
    signatureDescription: 'Ocean-fresh local Kingklip fillet and juicy flame-grilled prince prawns served hot off the grill with a delicate lemon garlic herb emulsion.',
    signatureIngredients: ['Fresh South African Kingklip', 'Ocean Wild Prawns', 'Lemon Garlic Emulsion', 'Fennel Sprigs'],
    digestiveNote: 'Kingklip is a lean white fish with good protein and low saturated fat. Freshly grilled seafood retains most of its nutritional value. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.codfather.co.za/',
    latitude: -33.9535,
    longitude: 18.3792,
    phone: '+27214380782',
    estimatedWait: '10 - 15 min'
  },
  {
    id: 'eat-fyn-dining',
    name: 'FYN Restaurant',
    address: '5th Floor, Parliament St, Cape Town City Centre',
    cuisine: 'Fine Brasserie',
    vibeMatch: 'feeling fancy',
    fallbackDistance: '0.8 km from Gardens',
    rating: 4.9,
    priceSymbol: 'RRRR',
    voucherOffer: 'Curated premium Cape dessert nectar glass paired with the final course',
    signatureOrder: 'Outeniqua Springbok with Kabocha Squash',
    signatureDescription: 'Seared tenderloin of wild Outeniqua Springbok paired with cured Kabocha squash puree, Cape gooseberry reduction, and dark cocoa nib crunch.',
    signatureIngredients: ['Outeniqua Springbok Tenderloin', 'Kabocha Squash Puree', 'Cape Gooseberries', 'Szechuan Pepper Dust'],
    digestiveNote: 'Springbok is a very lean game meat, low in fat and high in protein. Wild game typically has a different fat profile than farmed livestock. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://fynrestaurant.com/',
    latitude: -33.9262,
    longitude: 18.4215,
    phone: '+27212862733',
    estimatedWait: 'Booking Highly Recommended'
  },
  {
    id: 'eat-jonkershuis-constantia',
    name: 'Jonkershuis Constantia',
    address: 'Groot Constantia Rd, Constantia, Cape Town',
    cuisine: 'Premium Tapas',
    vibeMatch: 'treating myself',
    fallbackDistance: '14.1 km from City Bowl',
    rating: 4.7,
    priceSymbol: 'RRR',
    voucherOffer: 'A free traditional Cape Malay spiced koesister or sweet bite with any hot beverage',
    signatureOrder: 'Traditional Cape Malay Lamb Curry',
    signatureDescription: 'Tender lamb slow-simmered with traditional fragrant dry-roasted spices, ginger, garlic, apricot preserves, and toasted almond flakes.',
    signatureIngredients: ['Karoo Lamb Hindquarter', 'Cape Malay Curry Spice', 'Dried Apricot Compote', 'Fluffy Basmati Rice'],
    digestiveNote: 'Turmeric and cardamom are traditional Cape Malay spices with long culinary histories. Lamb provides protein and iron. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://jonkershuisconstantia.co.za/',
    latitude: -34.0287,
    longitude: 18.4252,
    phone: '+27217946255',
    estimatedWait: '15 - 20 min'
  },
  {
    id: 'eat-truth-coffee',
    name: 'Truth Coffee Roasting',
    address: '36 Buitenkant St, Cape Town City Centre',
    cuisine: 'Comfort Café',
    vibeMatch: 'tired & cosy',
    fallbackDistance: '1.1 km from Foreshore',
    rating: 4.7,
    priceSymbol: 'RR',
    voucherOffer: 'Gourmet take-home 100g sample packet of custom roast coffee beans with any full breakfast',
    signatureOrder: 'Steampunk French Toast & Maple Bacon',
    signatureDescription: 'Thick-battered brioche French toast topped with crispy wood-smoked bacon, maple syrup glaze, and artisanal double-cream Chantilly.',
    signatureIngredients: ['Artisanal Butter Brioche', 'Maple Glaze Coating', 'Double-Cream Chantilly', 'Wood-Smoked Bacon'],
    digestiveNote: 'Eggs and dairy in French toast provide protein and calcium. A satisfying, energy-dense breakfast to start the day. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://truth.coffee/',
    latitude: -33.9281,
    longitude: 18.4255,
    phone: '+27212000440',
    estimatedWait: '5 - 10 min'
  },
  {
    id: 'eat-jerrys-gardens',
    name: "Jerry's Burger Bar Gardens",
    address: '123 Kloof St, Gardens, Cape Town',
    cuisine: 'Artisan Burgers',
    vibeMatch: 'lazy Sunday energy',
    fallbackDistance: '1.2 km from City Bowl',
    rating: 4.6,
    priceSymbol: 'RR',
    voucherOffer: 'Get a complimentary half-pint of local craft draft beer with any stuffed burger order',
    signatureOrder: 'The Lucy Cheddar-Stuffed Burger',
    signatureDescription: '100% pure premium beef patty stuffed secretly with mature cheddar, grilled pink, and topped with caramelized white onions and smoky sweet glaze.',
    signatureIngredients: ['Premium Local Beef', 'Stuffed Cheddar Melt', 'Caramelized Onion', 'House Sweet Basting'],
    digestiveNote: 'Beef provides protein, zinc, and B12. Caramelised onions are simply cooked onions — sweeter and softer than raw. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://jerrysburgerbar.co.za/',
    latitude: -33.9315,
    longitude: 18.4069,
    phone: '+27214224415',
    estimatedWait: '10 - 15 min'
  },
  {
    id: 'eat-gold-restaurant',
    name: 'GOLD Restaurant',
    address: '15 Bennett St, Green Point, Cape Town',
    cuisine: 'Flame Grill / Spicy',
    vibeMatch: 'craving something bold & spicy',
    fallbackDistance: '2.5 km from City Bowl',
    rating: 4.8,
    priceSymbol: 'RRR',
    voucherOffer: 'Complimentary express African hand drumming experience entry voucher on booking arrival',
    signatureOrder: 'Zanzibari Fish Curry with Coconut Milk',
    signatureDescription: 'Fresh local linefish cooked with spicy Zanzibari curry spices, sweet thick coconut cream, fresh lemongrass, and local garden vegetables.',
    signatureIngredients: ['Fresh Cape Linefish', 'Aromatic Zanzibari Masala', 'Thick Coconut Milk', 'Steamed Lemongrass stalks'],
    digestiveNote: 'Coconut milk adds richness and some medium-chain fats. Fish curry is typically a lighter protein option compared to red meat dishes. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://goldrestaurant.co.za/',
    latitude: -33.9149,
    longitude: 18.4162,
    phone: '+27214214653',
    estimatedWait: 'Pre-booking Advised'
  },
  {
    id: 'eat-kloof-street-house',
    name: 'Kloof Street House',
    address: '50 Kloof St, Gardens, Cape Town',
    cuisine: 'Eclectic Brasserie',
    vibeMatch: 'need comfort food',
    fallbackDistance: '1.5 km from City Bowl',
    rating: 4.6,
    priceSymbol: 'RRR',
    voucherOffer: 'Enjoy a complimentary classic espresso martini or mocktail with any main meal',
    signatureOrder: 'Ostrich Fillet with Truffle Mash',
    signatureDescription: 'Pan-seared, grass-fed Karoo ostrich fillet rested on velvety truffle-infused potato puree with a dark balsamic reduction.',
    signatureIngredients: ['Karoo Ostrich', 'Truffle Oil', 'Potato Puree', 'Balsamic Reduction'],
    digestiveNote: 'Ostrich is one of the leanest red meats available, with high protein and low cholesterol. Popular for those watching saturated fat intake. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://kloofstreethouse.co.za/',
    latitude: -33.9298,
    longitude: 18.4116,
    phone: '+27214234413',
    estimatedWait: '20 - 30 min'
  },
  {
    id: 'eat-pot-luck-club',
    name: 'The Pot Luck Club',
    address: 'Silo Top Floor, The Old Biscuit Mill, Woodstock, Cape Town',
    cuisine: 'Global Tapas',
    vibeMatch: 'feeling fancy',
    fallbackDistance: '4.2 km from City Bowl',
    rating: 4.8,
    priceSymbol: 'RRRR',
    voucherOffer: 'An exclusive complimentary off-menu amuse-bouche sent by the chef',
    signatureOrder: 'Smoked Beef Fillet with Black Pepper & Truffle',
    signatureDescription: 'Slices of cold-smoked beef fillet layered with a rich black pepper and truffle cafe au lait sauce, finished with crisp parsnip ribbons.',
    signatureIngredients: ['Cold-Smoked Beef', 'Truffle Cafe au Lait', 'Parsnip Ribbons', 'Crushed Black Pepper'],
    digestiveNote: 'Beef provides complete protein and iron. Black pepper is a common spice that has been used in cooking for thousands of years. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://thepotluckclub.co.za/',
    latitude: -33.9275,
    longitude: 18.4627,
    phone: '+27214470804',
    estimatedWait: 'Booking Required'
  },
  {
    id: 'eat-baia-seafood',
    name: 'Baía Seafood Restaurant',
    address: 'Victoria Wharf, V&A Waterfront, Cape Town',
    cuisine: 'Fine Seafood',
    vibeMatch: 'craving something bold & spicy',
    fallbackDistance: '2.8 km from City Bowl',
    rating: 4.7,
    priceSymbol: 'RRRR',
    voucherOffer: 'A complimentary glass of private cellar Sauvignon Blanc with your seafood platter',
    signatureOrder: 'Mozambican LM Prawns with Peri-Peri',
    signatureDescription: 'Butterflied giant Mozambican prawns, grilled over an open flame with house-made, rich garlic and fiery peri-peri butter.',
    signatureIngredients: ['Giant LM Prawns', 'Peri-Peri Chilies', 'Garlic Butter Base', 'Lemon Wedges'],
    digestiveNote: 'Large prawns are a good source of lean protein and selenium. Grilling rather than frying keeps the dish lighter. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://baiarestaurant.co.za/',
    latitude: -33.9036,
    longitude: 18.4215,
    phone: '+27214210935',
    estimatedWait: '15 - 25 min'
  },
  {
    id: 'eat-mzansi',
    name: 'Mzansi Restaurant',
    address: '45 Harlem Ave, Langa, Cape Town',
    cuisine: 'Traditional South African',
    vibeMatch: 'need comfort food',
    fallbackDistance: '12.5 km from City Bowl',
    rating: 4.9,
    priceSymbol: 'R',
    voucherOffer: 'A traditional freshly baked steam bread (Umhqusho) portion on the house',
    signatureOrder: 'Traditional Slow-Cooked Beef Stew',
    signatureDescription: 'Deeply savory beef stew slow-cooked for hours with aromatic herbs, served authentically alongside samp and beans.',
    signatureIngredients: ['Local Beef Cuts', 'Samp (Crushed Corn)', 'Sugar Beans', 'Wild African Herbs'],
    digestiveNote: 'Samp and beans together are a complementary protein combination common in southern African cuisine, and a good source of dietary fibre. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://mzansirestaurant.co.za/',
    latitude: -33.9463,
    longitude: 18.5284,
    phone: '+27737113111',
    estimatedWait: '5 - 10 min'
  },
  {
    id: 'eat-test-kitchen',
    name: 'The Test Kitchen Fledgelings',
    address: 'Old Biscuit Mill, 375 Albert Rd, Woodstock',
    cuisine: 'Contemporary Global',
    vibeMatch: 'treating myself',
    fallbackDistance: '2.5 km from City Bowl',
    rating: 4.8,
    priceSymbol: 'RRR',
    voucherOffer: 'Complimentary welcoming aperitif',
    signatureOrder: 'Butter-Poached Langoustine',
    signatureDescription: 'Tender langoustine slow-poached in local farm butter, served with a citrus foam and smoked pearl onions.',
    signatureIngredients: ['Langoustine', 'Farm Butter', 'Citrus', 'Pearl Onions'],
    digestiveNote: 'Langoustine is a shellfish high in protein and low in fat. Fine dining portions are typically moderate in size. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://thetestkitchen.co.za/',
    latitude: -33.9272,
    longitude: 18.4552,
    phone: '+27214472337',
    estimatedWait: 'Pre-booking Required'
  },
  {
    id: 'eat-arnolds',
    name: 'Arnolds Restaurant',
    address: '60 Kloof St, Gardens, Cape Town',
    cuisine: 'South African Cafe',
    vibeMatch: 'lazy Sunday energy',
    fallbackDistance: '1.2 km from City Bowl',
    rating: 4.4,
    priceSymbol: 'RR',
    voucherOffer: 'Free filter coffee with any breakfast',
    signatureOrder: 'Gemsbok and Ostrich Carpaccio',
    signatureDescription: 'Thinly sliced game meat, served with a balsamic reduction, fresh rocket, and parmesan shavings.',
    signatureIngredients: ['Gemsbok', 'Ostrich', 'Balsamic', 'Rocket', 'Parmesan'],
    digestiveNote: 'Game meats like gemsbok and ostrich are generally leaner than conventional farmed meats. Carpaccio is served raw, so freshness is important. ⚕️ General wellness info — not medical advice.',
    externalLink: 'http://www.arnolds.co.za/',
    latitude: -33.9312,
    longitude: 18.4098,
    phone: '+27214244344',
    estimatedWait: '10 min'
  },
  {
    id: 'eat-clarkes',
    name: 'Clarkes Bar & Dining Room',
    address: '133 Bree St, Cape Town City Centre',
    cuisine: 'American Diner',
    vibeMatch: 'stressed, need quick and easy',
    fallbackDistance: '0 km from City Bowl',
    rating: 4.6,
    priceSymbol: 'RR',
    voucherOffer: '10% off the famous Cheeseburger',
    signatureOrder: 'The Classic Cheeseburger',
    signatureDescription: 'Smash patty style burger on a soft buttery brioche bun, classic American cheese, and house-made pickles.',
    signatureIngredients: ['Grass-fed Beef Patty', 'American Cheese', 'House Pickles', 'Brioche Bun'],
    digestiveNote: 'A classic smash burger with beef and cheese provides protein and fats for a filling, satisfying meal. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.clarkesdining.co.za/',
    latitude: -33.9213,
    longitude: 18.4172,
    phone: '+27874700165',
    estimatedWait: '15 min'
  },
  {
    id: 'eat-rust-en-vrede',
    name: 'Rust en Vrede Restaurant',
    address: 'Annandale Rd, Stellenbosch',
    cuisine: 'Classic French meets Cape',
    vibeMatch: 'feeling fancy',
    fallbackDistance: '45.0 km from City Bowl',
    rating: 4.9,
    priceSymbol: 'RRRR',
    voucherOffer: 'Complimentary glass of estate Syrah pairing',
    signatureOrder: 'Springbok Mignon',
    signatureDescription: 'Impeccably seared prime cut of springbok served with Pomme Anna, smoked bone marrow, and a rich Syrah jus.',
    signatureIngredients: ['Springbok', 'Bone Marrow', 'Syrah Jus', 'Pomme Anna'],
    digestiveNote: 'Springbok is a lean game meat with a rich flavour. Bone marrow has been consumed in many cultures as a fatty, nutrient-dense food. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://rustenvrede.com/',
    latitude: -34.0026,
    longitude: 18.8554,
    phone: '+27218813757',
    estimatedWait: 'Pre-booking Required'
  },
  {
    id: 'eat-tokara',
    name: 'Tokara Restaurant',
    address: 'Helshoogte Rd, Stellenbosch',
    cuisine: 'Modern South African',
    vibeMatch: 'treating myself',
    fallbackDistance: '52.0 km from City Bowl',
    rating: 4.8,
    priceSymbol: 'RRR',
    voucherOffer: 'Olive oil tasting from the estate on the house',
    signatureOrder: 'Fire-Roasted Celeriac',
    signatureDescription: 'Whole salt-baked celeriac with hazelnut crumbling, estate olive oil emulsion, and wild mushrooms.',
    signatureIngredients: ['Celeriac', 'Wild Mushrooms', 'Hazelnuts', 'Estate Olive Oil'],
    digestiveNote: 'Celeriac is a root vegetable with fibre, vitamin C, and potassium. A vegetable-forward dish like this is naturally lower in saturated fat. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.tokara.com/',
    latitude: -33.9189,
    longitude: 18.9189,
    phone: '+27218852550',
    estimatedWait: 'Pre-booking Required'
  },
  {
    id: 'eat-volkskombuis',
    name: 'De Volkskombuis',
    address: 'Aan de Wagenweg, Stellenbosch',
    cuisine: 'Traditional Cape Malay / Afrikaner',
    vibeMatch: 'need comfort food',
    fallbackDistance: '48.0 km from City Bowl',
    rating: 4.5,
    priceSymbol: 'RR',
    voucherOffer: 'A complimentary slice of traditional warm malva pudding',
    signatureOrder: 'Meraai se Hoenderpie',
    signatureDescription: 'A classic rich chicken pie baked under a flaky golden crust, served with sweet root vegetables and roast potatoes.',
    signatureIngredients: ['Free Range Chicken', 'Puff Pastry', 'Root Vegetables', 'Chicken Gravy'],
    digestiveNote: 'Slow-cooked chicken in a pie is a comforting, familiar dish. Free-range chicken has a slightly different fat profile than conventionally raised poultry. ⚕️ General wellness info — not medical advice.',
    externalLink: 'https://www.devolkskombuis.co.za/',
    latitude: -33.9392,
    longitude: 18.8541,
    phone: '+27217451111',
    estimatedWait: '20 min'
  }
];
